services:
  db:
    image: mysql:8.0
    container_name: adega_banco
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT_HOST:-3307}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./adega
    container_name: adega_server
    restart: on-failure
    ports:
      # Expor porta HTTP (host:8080 -> container:8080)
      - "${API_HTTP_PORT:-8080}:8080"
      # Expor porta HTTPS (host:8443 -> container:8443)
      - "${API_HTTPS_PORT:-8443}:8443"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Adicionando fallback para o nome do banco caso a variável falhe
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE:-adega}?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
      - API_SECURITY_TOKEN_SECRET=${API_SECURITY_TOKEN_SECRET}

  # ==========================================
  # NOVO SERVIÇO DE BACKUP
  # ==========================================
  backup:
    image: fradelg/mysql-cron-backup
    container_name: adega_backup
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
      # Define o intervalo (Padrão Cron). Ex: "0 3 * * *" significa todo dia às 03:00 da manhã
      - CRON_TIME=0 3 * * *
    
    volumes:
      # Mapeia uma pasta local chamada "meus_backups" na mesma pasta do projeto para guardar os arquivos .sql
      - ./meus_backups:/backup

volumes:
  db_data: