spring.application.name=adega

# Mantém apenas a porta e o endereço normais
server.port=8080
server.address=0.0.0.0

# Configurações do Banco de Dados (PostgreSQL do Render)
spring.datasource.url=${BANCO_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações para Docker (X-Forwarded)
server.forward-headers-strategy=native

# ⚠️ COMENTE OU REMOVA TOTALMENTE AS LINHAS DE SSL ABAIXO (ADICIONANDO '#' NA FRENTE):
# server.ssl.enabled=true
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:123456}
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=adega

# Configuração do Token
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}