spring.application.name=adega

# Porta e endereço padrão para ambiente web
server.port=8080
server.address=0.0.0.0

# -------------------------------------------------------------
# CONEXÃO DIRETA COM O POSTGRESQL DO RENDER (Valores Fixos)
# -------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://dpg-d8d5fpuk1jcs738kjg00-a.oregon-postgres.render.com/adega_banco
spring.datasource.username=adega_banco_user
spring.datasource.password=PHzjYREEGZT3hyrYqlppkoK38Zd8XcZj
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# -------------------------------------------------------------

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações para Docker (X-Forwarded)
server.forward-headers-strategy=native

# Mapeamento do segredo JWT vindo do ambiente
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}