spring.application.name=adega

# Configurações do Tomcat / Portas
server.port=8443
server.http.port=8080

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações de SSL/HTTPS
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:123456}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=adega

# MÁGICA AQUI: Define que o perfil padrão é o 'dev'
spring.profiles.active=dev